### ISSUE TITLE
Provide link to Slack invitation page

### ISSUE THREAD

**Issue by energydev** [techlahoma/techlahoma_lander#21]
Provide a link to the Slack invitation page on the Techlahoma lander.

**Comment by nsweaney** [comment]
Dude, we're going on 81 days here since @energydev suggested this.  Someone wake up the webmaster! :-)

**Comment by jagthedrummer** [comment]
What _is_ the URL for the slack invitation page?

**Comment by energydev** [comment]
@jagthedrummer http://slack.techlahoma.org/ is the URL

**Comment by amandaharlin** [comment]
Since out of state recruiters are already joining the slack, do we want to
make it even more public? Maybe we should hold off on this until we have a
slackbot auto welcome messaging system in place that tells folks the
expected behavior (join to talk about tech, post jobs on the job board,
etc). Not that this will definitely become a problem, but if we get overrun
with recruiters and business looking to find employees for free or use the
community to their financial benefit, some people might stop participating.
Just my $0.02.

**Comment by nsweaney** [comment]
I'm not a fan of locking things down just in case it might be a problem.
Preventing folks from participating in case others might stop participating
seems counter-productive.

Another option is to add the expected behavior stuff on the invitation
page. Make them read it & answer a question about it along with their email
address to get the invitation.  Then temp ban folks that become a problem.

**Comment by energydev** [comment]
I agree with @nsweaney I'm not for locking this down, plus, multiple members of our Slack community have mentioned a desire for this feature. I do like the idea of having our Slack policy being visible and agreed to before they join. If that would take too much time then I recommend on the invitation page have clear text that says something about no job postings on the Slack channel.

**Comment by amandaharlin** [comment]
Putting that text with the link to join sounds like it solves the problem.
Awesome job you two, that's a great solution.

**Comment by jagthedrummer** [comment]
This all sounds good. 👍 

What's the process for getting the appropriate text added to slack.techlahoma.org? I looked for a repo in the Techlahoma organization on GitHub, but I don't find anything that looks like an obvious candidate for where to open that particular issue.

**Comment by amandaharlin** [comment]
just so y'all know we have a link on the new site with a slack invite on techlahoma.org/spaces
